<?php

namespace SYSOTEL\OTA\Common\Helpers;

class Enums
{
    const CHANNEL_ID_TRAVELBABU = 'TRAVELBABU';


    const MARKET_SEGMENT_B2C = 'B2C';
    const MARKET_SEGMENT_B2B = 'B2B';
    const MARKET_SEGMENT_CORPORATE = 'CORPORATE';

    const BASE_CURRENCY_INR = 'INR';

    const AGE_CODE_ADULT = 'A';
    const AGE_CODE_CHILD = 'C';

    const BOOKING_STATUS_ATTEMPT = 'ATTEMPT';
    const BOOKING_STATUS_EXPIRED = 'EXPIRED';
    const BOOKING_STATUS_FAILED = 'FAILED';
    const BOOKING_STATUS_CONFIRMED = 'CONFIRMED';
    const BOOKING_STATUS_CANCELLED = 'CANCELLED';
    const BOOKING_STATUS_MODIFIED = 'MODIFIED';
}