<?php

namespace SYSOTEL\OTA\Common\Helpers;

class Enums
{
    const BOOKING_SOURCE_TRAVELBABU = 'TRAVELBABU';

    const MARKET_SEGMENT_B2C = 'B2C';
    const MARKET_SEGMENT_B2B = 'B2B';
    const MARKET_SEGMENT_CORPORATE = 'CORPORATE';

    const BASE_CURRENCY_INR = 'INR';

    const AGE_CODE_ADULT = 'A';
    const AGE_CODE_CHILD = 'C';

    const BOOKING_STATUS_ATTEMPT = 'ATTEMPT';
    const BOOKING_STATUS_EXPIRED = 'EXPIRED';
    const BOOKING_STATUS_FAILED = 'FAILED';
    const BOOKING_STATUS_CONFIRMED = 'CONFIRMED';
    const BOOKING_STATUS_CANCELLED = 'CANCELLED';
    const BOOKING_STATUS_MODIFIED = 'MODIFIED';

    const PG_GROUP_PREPAID_CARD = 'PREPAID_CARD';
    const PG_GROUP_CREDIT_CARD = 'CREDIT_CARD';
    const PG_GROUP_CREDIT_CARD_EMI = 'CREDIT_CARD_EMI';
    const PG_GROUP_DEBIT_CARD_EMI = 'DEBIT_CARD_EMI';
    const PG_GROUP_DEBIT_CARD = 'DEBIT_CARD';
    const PG_GROUP_UPI_CREDIT_CARD = 'UPI_CREDIT_CARD';
    const PG_GROUP_PAYPAL = 'PAYPAL';
    const PG_GROUP_NET_BANKING = 'NET_BANKING';
    const PG_GROUP_CARDLESS_EMI = 'CARDLESS_EMI';
    const PG_GROUP_BANK_TRANSFER = 'BANK_TRANSFER';
    const PG_GROUP_PAY_LATER = 'PAY_LATER';
    const PG_GROUP_WALLET = 'WALLET';
    const PG_GROUP_UPI_PPI = 'UPI_PPI';
    const PG_GROUP_UPI_PPI_OFFLINE = 'UPI_PPI_OFFLINE';
}